name: Deploy Theme
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Ghost Theme
        continue-on-error: false
        uses: sredevopsdev/action-deploy-theme@main
        with:
          api-url: ${{ secrets.SREDEVOPS_API_URL }}
          api-key: ${{ secrets.SREDEVOPS_ADMIN_API_KEY }}
